### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by avishnyakov** [microsoft/Requirements#59]
Hi team, 

Interesting project, thank you for putting effort and open-sourcing this.
Can be very useful PS_based replacement of ServerSpec, InSpec and other non-PS based tools.

That said, can you please mention the status of this project?
Eg., who and how works on this, what is the roadmap and future, will it be supported in a long run or just abandoned at some point?

All this is useful to make informed decision on Requirements usage.

**Comment by chriskuech** [comment]
Requirements v2 merges together, cleans up, and open sources a few different declarative frameworks I wrote for Dynamics (including Requirements v1).  It's not officially supported/funded by Microsoft.

I plan to at least add support for PowerShell 7 DSC resources, using Requirements as a lightweight single-process LCM.  Parallel invocation of Requirements is also under consideration, but I have some concerns about implementing it. The backlog is otherwise empty, though open to feature requests.  It's also semantically versioned if you're worried about future changes.

This module is intentionally lightweight and written entirely in PowerShell.  The [core implementation](https://github.com/microsoft/Requirements/blob/master/src/core.ps1) isn't even 100 lines long.  You can easily just fork it and modify it to fit your needs if you can't use community modules.  It would still be easier to manage than not using a framework for idempotence.

**Comment by avishnyakov** [comment]
Sounds good, thank you.

Microsoft seems to have hundreds of abandoned repositories, hence asked. 
Seems there is an opportunity to improve governance and save some time for everyone.

**Comment by FireHelmet** [comment]
Hello @chriskuech 

I'm also interested to use this module but I would like to know the overall status of your project and also about Requirements v2.

- Have you released(or planned) this v2?
- Does this project is still maintained ?
- Is it compatible with PowerShell 7?

Thanks! and many thanks for your work so far!

**Comment by chriskuech** [comment]
Hello @FireHelmet,

* V2 has been released for over a year
* I implemented my entire feature backlog and no known bugs, but otherwise not maintained
* I just tried running Requirements' unit tests with pwsh 7, but they all failed.  Not sure if there is an issue with tests or the actual module.

I just left Microsoft and its but I'm building a new infra system so I might reanimate this repo, but otherwise no planned work here.  I can still approve PRs if you want to fix it
